project:
  type: website
  output-dir: docs
  render:
    - index.qmd
  resources:
    - CNAME
    - files/potter-cv.pdf

website:
  title: "Nicholas Potter"
  favicon: images/favicon.ico

format:
  html:
    theme: cosmo
    toc: false
    from: markdown-smart
